version: '3'

services:
  bcl2fastq:
    image: dceoy/bcl2fastq
    container_name: bcl2fastq
  bowtie2:
    image: dceoy/bowtie2
    container_name: bowtie2
  bwa:
    image: dceoy/bwa
    container_name: bwa
  cutadapt:
    image: dceoy/cutadapt
    container_name: cutadapt
  fastqc:
    image: dceoy/fastqc
    container_name: fastqc
  gatk:
    image: dceoy/gatk
    container_name: gatk
  picard:
    image: dceoy/picard
    container_name: picard
  prinseq:
    image: dceoy/prinseq
    container_name: prinseq
  rsem:
    image: dceoy/rsem
    container_name: rsem
  samtools:
    image: dceoy/samtools
    container_name: samtools
  star:
    image: dceoy/star
    container_name: star
  tophat:
    image: dceoy/tophat
    container_name: tophat
  trimmomatic:
    image: dceoy/trimmomatic
    container_name: trimmomatic
  jbrowse:
    image: jbrowse/gmod-jbrowse
    container_name: jbrowse
