---
version: '3'

services:
  abra:
    build:
      context: abra
    image: dceoy/abra:latest
  annovar:
    build:
      context: annovar
    image: dceoy/annovar:latest
  ascat:
    build:
      context: ascat
    image: dceoy/ascat:latest
  bcl2fastq:
    build:
      context: bcl2fastq
    image: dceoy/bcl2fastq:latest
  bcftools:
    build:
      context: bcftools
    image: dceoy/bcftools:latest
  bedtools:
    build:
      context: bedtools
    image: dceoy/bedtools:latest
  bowtie2:
    build:
      context: bowtie2
    image: dceoy/bowtie2:latest
  bwa:
    build:
      context: bwa
    image: dceoy/bwa:latest
  cufflinks:
    build:
      context: cufflinks
    image: dceoy/cufflinks:latest
  cutadapt:
    build:
      context: cutadapt
    image: dceoy/cutadapt:latest
  deepvariant:
    image: gcr.io/deepvariant-docker/deepvariant:latest
  deepvariant_gpu:
    image: gcr.io/deepvariant-docker/deepvariant_gpu:latest
  delly:
    build:
      context: delly
    image: dceoy/delly:latest
  elprep:
    build:
      context: elprep
    image: dceoy/elprep:latest
  fastq-dump:
    build:
      context: fastq-dump
    image: dceoy/fastq-dump:latest
  fastqc:
    build:
      context: fastqc
    image: dceoy/fastqc:latest
  gatk:
    build:
      context: gatk
    image: dceoy/gatk:latest
  hisat2:
    build:
      context: hisat2
    image: dceoy/hisat2:latest
  igv:
    build:
      context: igv
    image: dceoy/igv:latest
  jbrowse:
    build:
      context: jbrowse
    image: dceoy/jbrowse:latest
  last:
    build:
      context: last
    image: dceoy/last:latest
  macs2:
    build:
      context: macs2
    image: dceoy/macs2:latest
  msisensor:
    build:
      context: msisensor
    image: dceoy/msisensor:latest
  oncotator:
    build:
      context: oncotator
    image: dceoy/oncotator:latest
  picard:
    build:
      context: picard
    image: dceoy/picard:latest
  pindel:
    build:
      context: pindel
    image: dceoy/pindel:latest
  prinseq:
    build:
      context: prinseq
    image: dceoy/prinseq:latest
  rsem:
    build:
      context: rsem
    image: dceoy/rsem:latest
  samtools:
    build:
      context: samtools
    image: dceoy/samtools:latest
  snpeff:
    build:
      context: snpeff
    image: dceoy/snpeff:latest
  star:
    build:
      context: star
    image: dceoy/star:latest
  strelka:
    build:
      context: strelka
    image: dceoy/strelka:latest
  trimmomatic:
    build:
      context: trimmomatic
    image: dceoy/trimmomatic:latest
  varscan:
    build:
      context: varscan
    image: dceoy/varscan:latest
